name: UNIVR Fellowship Crawler

on:
  schedule:
    # Run every day at 08:00 UTC
    - cron: "0 8 * * *"
  workflow_dispatch: # allow manual trigger

#env:
#  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions: {}  # no GitHub token permissions needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv (cache enabled)
        uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true

      - name: Install dependencies
        run: uv python install

      - name: Install uv dependencies
        run: uv sync


      - name: Run crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: uv run crawler.py
